# PIPELINE DEFINITION
# Name: clean-experiment
# Inputs:
#    url: str
components:
  comp-clear-data:
    executorLabel: exec-clear-data
    inputDefinitions:
      artifacts:
        pod_path:
          artifactType:
            schemaTitle: system.Artifact
            schemaVersion: 0.0.1
  comp-download-data-and-output-pod-name:
    executorLabel: exec-download-data-and-output-pod-name
    inputDefinitions:
      parameters:
        url:
          parameterType: STRING
    outputDefinitions:
      artifacts:
        data_path:
          artifactType:
            schemaTitle: system.Artifact
            schemaVersion: 0.0.1
        pod_path:
          artifactType:
            schemaTitle: system.Artifact
            schemaVersion: 0.0.1
  comp-mock-model:
    executorLabel: exec-mock-model
    inputDefinitions:
      artifacts:
        data_path:
          artifactType:
            schemaTitle: system.Artifact
            schemaVersion: 0.0.1
    outputDefinitions:
      artifacts:
        model_path:
          artifactType:
            schemaTitle: system.Artifact
            schemaVersion: 0.0.1
  comp-sign-artefact:
    executorLabel: exec-sign-artefact
    inputDefinitions:
      artifacts:
        artefact_path:
          artifactType:
            schemaTitle: system.Artifact
            schemaVersion: 0.0.1
deploymentSpec:
  executors:
    exec-clear-data:
      container:
        args:
        - --pod-path
        - '{{$.inputs.artifacts[''pod_path''].path}}'
        command:
        - python3
        - /app/deleteRunPods.py
        image: endocker299/clean-pods:latest
    exec-download-data-and-output-pod-name:
      container:
        args:
        - --url
        - '{{$.inputs.parameters[''url'']}}'
        - --pod-path
        - '{{$.outputs.artifacts[''pod_path''].path}}'
        - --data-path
        - '{{$.outputs.artifacts[''data_path''].path}}'
        command:
        - python3
        - /app/downloadData.py
        image: endocker299/download-data:latest
    exec-mock-model:
      container:
        args:
        - --executor_input
        - '{{$}}'
        - --function_to_execute
        - mock_model
        command:
        - sh
        - -c
        - "\nif ! [ -x \"$(command -v pip)\" ]; then\n    python3 -m ensurepip ||\
          \ python3 -m ensurepip --user || apt-get install python3-pip\nfi\n\nPIP_DISABLE_PIP_VERSION_CHECK=1\
          \ python3 -m pip install --quiet --no-warn-script-location 'kfp==2.13.0'\
          \ '--no-deps' 'typing-extensions>=3.7.4,<5; python_version<\"3.9\"'  &&\
          \  python3 -m pip install --quiet --no-warn-script-location 'pandas' &&\
          \ \"$0\" \"$@\"\n"
        - sh
        - -ec
        - 'program_path=$(mktemp -d)


          printf "%s" "$0" > "$program_path/ephemeral_component.py"

          _KFP_RUNTIME=true python3 -m kfp.dsl.executor_main                         --component_module_path                         "$program_path/ephemeral_component.py"                         "$@"

          '
        - "\nimport kfp\nfrom kfp import dsl\nfrom kfp.dsl import *\nfrom typing import\
          \ *\n\ndef mock_model(data_path: InputPath(), model_path: OutputPath()):\n\
          \    import pandas as pd\n    import pickle\n\n    df = pd.read_csv(data_path)\n\
          \    with open(model_path, 'wb') as f:\n        pickle.dump(df, f)\n   \
          \ f.close()\n    print(df.head(3))\n\n"
        image: python:3.10
    exec-sign-artefact:
      container:
        args:
        - --artefact-path
        - '{{$.inputs.artifacts[''artefact_path''].path}}'
        command:
        - python3
        - /app/sign.py
        image: endocker299/sign-artefact:latest
pipelineInfo:
  name: clean-experiment
root:
  dag:
    tasks:
      clear-data:
        cachingOptions:
          enableCache: true
        componentRef:
          name: comp-clear-data
        dependentTasks:
        - download-data-and-output-pod-name
        - sign-artefact
        inputs:
          artifacts:
            pod_path:
              taskOutputArtifact:
                outputArtifactKey: pod_path
                producerTask: download-data-and-output-pod-name
        taskInfo:
          name: clear-data
      download-data-and-output-pod-name:
        cachingOptions:
          enableCache: true
        componentRef:
          name: comp-download-data-and-output-pod-name
        inputs:
          parameters:
            url:
              componentInputParameter: url
        taskInfo:
          name: download-data-and-output-pod-name
      mock-model:
        cachingOptions:
          enableCache: true
        componentRef:
          name: comp-mock-model
        dependentTasks:
        - download-data-and-output-pod-name
        inputs:
          artifacts:
            data_path:
              taskOutputArtifact:
                outputArtifactKey: data_path
                producerTask: download-data-and-output-pod-name
        taskInfo:
          name: mock-model
      sign-artefact:
        cachingOptions:
          enableCache: true
        componentRef:
          name: comp-sign-artefact
        dependentTasks:
        - mock-model
        inputs:
          artifacts:
            artefact_path:
              taskOutputArtifact:
                outputArtifactKey: model_path
                producerTask: mock-model
        taskInfo:
          name: sign-artefact
  inputDefinitions:
    parameters:
      url:
        parameterType: STRING
schemaVersion: 2.1.0
sdkVersion: kfp-2.13.0
