# PIPELINE DEFINITION
# Name: clean-experiment
# Inputs:
#    url: str
components:
  comp-clear-pods:
    executorLabel: exec-clear-pods
    inputDefinitions:
      parameters:
        pod_path:
          parameterType: STRING
  comp-download-data-and-output-pod-name:
    executorLabel: exec-download-data-and-output-pod-name
    inputDefinitions:
      parameters:
        url:
          parameterType: STRING
    outputDefinitions:
      artifacts:
        data_path:
          artifactType:
            schemaTitle: system.Artifact
            schemaVersion: 0.0.1
        pod_path:
          artifactType:
            schemaTitle: system.Artifact
            schemaVersion: 0.0.1
  comp-print-csv:
    executorLabel: exec-print-csv
    inputDefinitions:
      artifacts:
        data_path:
          artifactType:
            schemaTitle: system.Artifact
            schemaVersion: 0.0.1
    outputDefinitions:
      artifacts:
        model_path:
          artifactType:
            schemaTitle: system.Artifact
            schemaVersion: 0.0.1
deploymentSpec:
  executors:
    exec-clear-pods:
      container:
        command:
        - python3
        - /app/deleteRunPods.py
        - --pod-path
        - '{{$.inputs.parameters[''pod_path'']}}'
        image: endocker299/clean-pods:latest
    exec-download-data-and-output-pod-name:
      container:
        args:
        - --url
        - '{{$.inputs.parameters[''url'']}}'
        - --pod-path
        - '{{$.outputs.artifacts[''pod_path''].path}}'
        - --data-path
        - '{{$.outputs.artifacts[''data_path''].path}}'
        command:
        - python3
        - /app/downloadData.py
        image: endocker299/download-data:latest
    exec-print-csv:
      container:
        args:
        - --executor_input
        - '{{$}}'
        - --function_to_execute
        - print_csv
        command:
        - sh
        - -c
        - "\nif ! [ -x \"$(command -v pip)\" ]; then\n    python3 -m ensurepip ||\
          \ python3 -m ensurepip --user || apt-get install python3-pip\nfi\n\nPIP_DISABLE_PIP_VERSION_CHECK=1\
          \ python3 -m pip install --quiet --no-warn-script-location 'kfp==2.13.0'\
          \ '--no-deps' 'typing-extensions>=3.7.4,<5; python_version<\"3.9\"'  &&\
          \  python3 -m pip install --quiet --no-warn-script-location 'pandas' &&\
          \ \"$0\" \"$@\"\n"
        - sh
        - -ec
        - 'program_path=$(mktemp -d)


          printf "%s" "$0" > "$program_path/ephemeral_component.py"

          _KFP_RUNTIME=true python3 -m kfp.dsl.executor_main                         --component_module_path                         "$program_path/ephemeral_component.py"                         "$@"

          '
        - "\nimport kfp\nfrom kfp import dsl\nfrom kfp.dsl import *\nfrom typing import\
          \ *\n\ndef print_csv(data_path: InputPath(), model_path: OutputPath()):\n\
          \    import pandas as pd\n    df = pd.read_csv(data_path)\n    index = df.index\n\
          \    number_of_rows = len(index)\n    f = open(model_path, \"w\")\n    f.write('Number\
          \ of lines in dataset: ' + str(number_of_rows))\n    f.close()\n    print(df.head(3))\n\
          \n"
        image: python:3.10
pipelineInfo:
  name: clean-experiment
root:
  dag:
    tasks:
      clear-pods:
        cachingOptions:
          enableCache: true
        componentRef:
          name: comp-clear-pods
        dependentTasks:
        - print-csv
        inputs:
          parameters:
            pod_path:
              runtimeValue:
                constant: '{{channel:task=download-data-and-output-pod-name;name=pod_path;type=system.Artifact@0.0.1;}}'
        taskInfo:
          name: clear-pods
      download-data-and-output-pod-name:
        cachingOptions:
          enableCache: true
        componentRef:
          name: comp-download-data-and-output-pod-name
        inputs:
          parameters:
            url:
              componentInputParameter: url
        taskInfo:
          name: download-data-and-output-pod-name
      print-csv:
        cachingOptions:
          enableCache: true
        componentRef:
          name: comp-print-csv
        dependentTasks:
        - download-data-and-output-pod-name
        inputs:
          artifacts:
            data_path:
              taskOutputArtifact:
                outputArtifactKey: data_path
                producerTask: download-data-and-output-pod-name
        taskInfo:
          name: print-csv
  inputDefinitions:
    parameters:
      url:
        parameterType: STRING
schemaVersion: 2.1.0
sdkVersion: kfp-2.13.0
